name: contextual
description: Um jogo de adivinhação de palavras baseado em proximidade semântica.
publish_to: 'none'
#version: 1.0.2+1 IOS
version: 1.0.4+0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  lottie: ^3.3.1
  flutter_svg: ^2.0.17

  games_services: ^4.1.0

  package_info_plus: ^8.3.0

  in_app_purchase: ^3.2.1

  timezone: ^0.10.0

  # Gerenciamento de Estado
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  dartz: ^0.10.1

  # Armazenamento Local
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5

  # Redes e APIs
  http: ^1.3.0
  dio: ^5.8.0+1

  # Google NLP API
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0

  google_mobile_ads: ^5.3.1

  smooth_page_indicator: ^1.2.1
  confetti: ^0.8.0

  # Internacionalização
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # Compartilhamento
  share_plus: ^10.1.4

  # Utilitários
  collection: ^1.19.1
  uuid: ^4.5.1
  logger: ^2.5.0
  url_launcher: ^6.3.1

  # Firebase
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/credentials/
    - assets/animations/
    - assets/icons/
    - assets/words/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
